---
# TODO: add namespace visual-studio-code
#
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: visual-studio-code
  # TODO: add next line, after namespace visual-studio-code is installed
  #namespace: visual-studio-code
  labels:
    app: visual-studio-code
spec:
  replicas: 1
  selector:
    matchLabels:
      app: visual-studio-code
  template:
    metadata:
      labels:
        app: visual-studio-code
    spec:
      containers:
      - name: visual-studio-code
#        image: beneventsur/visual-studio-code:1.34.0-nodejs-v10.16.0
        image: vocon/visual-studio-code
        env:
        - name: WIDTH
          value: "1920"
        - name: HEIGHT
          value: "1080"
        - name: PASSWORD
          value: "8345682346378"
        ports:
        - containerPort: 6080
          hostPort: 6902
          name: browser
        - containerPort: 5901
          hostPort: 5902
          name: vnc
        volumeMounts:
        - mountPath: /home/centos
          name: home-volume
        - mountPath: /home/user
          name: vocloud-volume
        - mountPath: /home/user/.IdeaIC2019.3
          name: idea-config-volume
        - mountPath: /home/user/.local
          name: idea-local-volume
        - mountPath: /home/user/git
          name: git-volume
        - mountPath: /home/user/.java
          name: java-config
        - mountPath: /home/user/.m2
          name: maven-config
        - mountPath: /home/user/.ssh
          name: dot-ssh
        - mountPath: /dev/shm
          name: dev-shm
      volumes:
      - name: home-volume
        hostPath:
          path: /home/centos
          type: Directory
      - name: vocloud-volume
        hostPath:
          path: /home/centos/.vocloud
          type: Directory
      - name: idea-config-volume
        hostPath:
          path: /home/centos/.vocloud/.IdeaIC2019.3
          type: Directory
      - name: idea-local-volume
        hostPath:
          path: /home/centos/.vocloud/.local
          type: Directory
      - name: git-volume
        hostPath:
          path: /home/centos/git
          type: Directory
      - name: java-config
        hostPath:
          path: /home/centos/.vocloud/.java
          type: Directory
      - name: maven-config
        hostPath:
          path: /home/centos/.vocloud/.m2
          type: Directory
      - name: dot-ssh
        hostPath:
          path: /home/centos/.ssh
          type: Directory
      - name: dev-shm
        emptyDir:
          medium: Memory
#        persistentVolumeClaim:
#          claimName: visual-studio-code-claim
